spring:
  application:
    name: rastreadorpedido

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:app.db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/rastreador

logging:
  level:
    org.hibernate.SQL: DEBUG